package com.smashstats;

public class Constants {
    public static final int NUM_FIGHTERS = 78;
    public static final int NUM_STAGES = 103;
    public static final String[] LIST_OF_FIGHTERS = {
            "Bayonetta",
            "Bowser",
            "Bowser Jr.",
            "Captain Falcon",
            "Charizard",
            "Chrom",
            "Cloud",
            "Corrin",
            "Daisy",
            "Dark Pit",
            "Dark Samus",
            "Diddy Kong",
            "Donkey Kong",
            "Dr. Mario",
            "Duck Hunt",
            "Falco",
            "Fox",
            "Ganondorf",
            "Greninja",
            "Ice Climbers",
            "Ike",
            "Inkling",
            "Isabelle",
            "Incineroar",
            "Ivysaur",
            "Jigglypuff",
            "Joker",
            "Ken",
            "King Dedede",
            "King K. Rool",
            "Kirby",
            "Link",
            "Little Mac",
            "Lucario",
            "Lucas",
            "Lucina",
            "Luigi",
            "Mario",
            "Marth",
            "Mega Man",
            "Meta Knight",
            "Mewtwo",
            "Mii Brawler",
            "Mii Swordfighter",
            "Mii Gunner",
            "Mr. Game & Watch",
            "Ness",
            "Olimar",
            "Pac-Man",
            "Palutena",
            "Peach",
            "Pichu",
            "Pikachu",
            "Piranha Plant",
            "Pit",
            "Richter",
            "Ridley",
            "R.O.B.",
            "Robin",
            "Rosalina & Luma",
            "Roy",
            "Ryu",
            "Samus",
            "Sheik",
            "Shulk",
            "Simon",
            "Snake",
            "Sonic",
            "Squirtle",
            "Toon Link",
            "Villager",
            "Wario",
            "Wii Fit Trainer",
            "Wolf",
            "Yoshi",
            "Young Link",
            "Zelda",
            "Zero Suit Samus"
    };
}
